DROP DATABASE IF EXISTS employeedata_db;
CREATE DATABASE employeedata_db;

USE employeedata_db;

CREATE TABLE department (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  dept_name VARCHAR(30) NOT NULL,
);

CREATE TABLE role (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  
)

